data:
  build: . 
  volumes:
    - /home/wordpress
    - /var/ssl:/home/wordpress/conf/certs
  command: /bin/true
web:
  build: . 
  links:
    - mysql
    - redis
    - memcached
  env_file: .env
  volumes_from:
    - data
nginx:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /var/ssl:/etc/nginx/certs
    - /var/run/docker.sock:/tmp/docker.sock:ro
mysql:
  image: mariadb
  env_file: .env
redis:
  image: redis
memcached:
  image: memcached
